version: "3.8"

services:
    nginx:
        image: 'nginx:latest'
        container_name: nginx
        restart: always
        ports:
            - "${APP_PORT}:80"
            - "443:443"
        tty: true
        volumes:
            # - ./:/var/www
            - .docker/nginx/conf.d/:/etc/nginx/conf.d/
        volumes_from:
            - app
        networks:
            - storage-network
        links:
            - app
        depends_on:
            - app
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                user: "${USER}"
                uid: "${UID}"
        restart: always
        image: app
        tty: true
        hostname: app
        container_name: app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "${APP_PORT}:9000"
        environment:
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        networks:
            - storage-network
        links:
            - mysql
            - redis
        depends_on:
            - mysql
            - redis
            - phpmyadmin

    redis:
        image: redis:latest
        container_name: redis
        restart: always
        hostname: ${REDIS_HOST}

        ports:
            - "${REDIS_PORT}:6379"
        volumes:
            - 'data-redis:/data'
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        networks:
            - storage-network
        command: redis-server --requirepass "${REDIS_PASSWORD}"
        healthcheck:
            test: [ "CMD", "redis-cli", "ping", "-p${REDIS_PASSWORD}" ]
            retries: 3
            timeout: 5s

    mysql:
        image: mysql:8.0
        container_name: mysql
        hostname: mysql
        restart: always

        ports:
            - "${DB_PORT}:3306"
        volumes:
            - 'data-mysql:/var/lib/mysql'
        networks:
            - storage-network
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        depends_on:
            - mysql
        environment:
            - PMA_HOSTS = mysql:${DB_PORT}
            - PMA_PORT = 3008,3007,3006
            - PMA_USER = 'root'
            - PMA_PASSWORD = '${DB_PASSWORD}'
            - PMA_ARBITRARY = 1
        networks:
            - storage-network

networks:
    storage-network:
        driver: bridge
volumes:
    data-mysql:
        driver: local
    data-redis:
        driver: local
