enum ActionTypes {
    // App
    SET_LOADING = "SET_LOADING",
    APP_START_UP_COMPLETE = "APP_START_UP_COMPLETE",
    SET_CONTENT_OF_CONFIRM_MODAL = "SET_CONTENT_OF_CONFIRM_MODAL",
    SET_INFO_PAGE = "SET_INFO_PAGE",
    CHANGE_LANGUAGE = "CHANGE_LANGUAGE",
    SET_CONFIG = "SET_CONFIG",
    SET_NOTICE = "SET_NOTICE",
    CLEAR_NOTICE = "CLEAR_NOTICE",
    SET_THEME = "SET_THEME",
    // Admin
    SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN",
    CLEAR_ACCESS_TOKEN = "CLEAR_ACCESS_TOKEN",
    SET_REFRESH_TOKEN = "SET_REFRESH_TOKEN",
    CLEAR_REFRESH_TOKEN = "CLEAR_REFRESH_TOKEN",
    PROCESS_LOGOUT = "PROCESS_LOGOUT",
    SET_ADMIN = "SET_ADMIN",
    UNSET_ADMIN = "UNSET_ADMIN",

    // User
    USER_LOGOUT = "USER_LOGOUT",
    SET_USER = "SET_USER",
    UNSET_USER = "UNSET_USER",

    // File Manager
    SET_HISTORY_FM = "SET_HISTORY_FM",
    SET_CONFIG_FM = "SET_CONFIG_FM",
    SET_MODE = "SET_MODE",
    SET_DISKS = "SET_DISKS",
    SELECT_DISK = "SELECT_DISK",
    SET_DIRECTORIES = "SET_DIRECTORIES",
    SELECT_DIRECTORY = "SELECT_DIRECTORY",
    SET_FILES = "SET_FILES",
    SET_SELECTED = "SET_SELECTED",
    SET_TREE = "SET_TREE",
    SET_CLIPBOARD = "SET_CLIPBOARD",
    CLEAR_CLIPBOARD = "CLEAR_CLIPBOARD",
}

export default ActionTypes;
