<?php
 return array (
  'disk' => 'nextcloud',
  'disk_client' => 'http://cloud.min-services.com',
  'disk_client_id' => 'Min',
  'disk_client_secret' => '8LACa-6wSwo-DJmpa-CwiGZ-9C7dP',
  'smtp_template' => 'default',
  'smtp_host' => 'smtp.gmail.com',
  'smtp_port' => '587',
  'smtp_username' => 'hotro.minservice@gmail.com',
  'smtp_password' => 'ugvoeswlfphvsxvv',
  'smtp_encryption' => 'TLS',
  'smtp_from_address' => 'Min Services',
  'smtp_rate_limit' => 30,
  'logo' => 'http://127.0.0.1:8000/storage/Storage/logo.png',
  'safe_mode_enable' => 0,
  'stop_register' => 0,
  'email_verify' => 0,
  'app_name' => 'Min Services',
  'app_url' => 'http://127.0.0.1:8000',
  'recaptcha_enable' => 0,
  'recaptcha_site_key' => '6Ld6fSMbAAAAAK7MAgYePB608RUPBIgu2AvIXwpg',
  'recaptcha_secret' => '6Ld6fSMbAAAAAIlkJ-GsJnBXaghgyRJWTNqN1o3s',
  'telegram_bot_enable' => 0,
  'telegram_bot_token' => NULL,
) ;
